### ISSUE TITLE
About the Interceptor in OkHttp

### ISSUE THREAD

**Issue by shangmingchao** [TWiStErRob/glide-support#1]
Hi.
I copied your code in the [_232_progress](https://github.com/TWiStErRob/glide-support/tree/master/src/glide3/java/com/bumptech/glide/supportapp/github/_232_progress), but it did't work. Please help me to review that [repo](https://github.com/shangmingchao/ProgressGlide) in the Github. It stumped me all day. help me please...

**Comment by IRMobydick** [comment]
Hi there, And How can use this progress target for `GIF` image?
And is there any chance to detect `GIF` image is animated or not?

**Comment by aftabsikander** [comment]
@Teovald @shangmingchao I have the same issue, I followed same example line by line and the [gist](https://gist.github.com/TWiStErRob/08d5807e396740e52c90) still I am unable to get real download progress.

**Comment by shangmingchao** [comment]
@aftabsikander I can be solved if don't use the `com.bumptech.glide.integration.okhttp3.OkHttpGlideModule`(don't import com.github.bumptech.glide:okhttp3-integration:1.4.0@aar), I think there's maybe something wrong when Glide init `GlideModule`s

**Comment by aftabsikander** [comment]
@shangmingchao Can you please provide me a sample project so that I can see what I did wrong.

**Comment by shangmingchao** [comment]
@aftabsikander Just delete the integration library(compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar') and modify this
```xml
        <meta-data
            android:name="com.bumptech.glide.integration.okhttp3.OkHttpGlideModule"
            tools:node="remove" />
        <meta-data
            android:name="com.frank.progressglide.OkHttpProgressGlideModule"
            android:value="GlideModule" />
```
to
```xml
        <meta-data
            android:name="com.frank.progressglide.OkHttpProgressGlideModule"
            android:value="GlideModule" />
```
and create `OkHttpStreamFetcher.java`, `OkHttpUrlLoader.java` files just like integration library did.
then it works. But I don't know why it doesn't work in the previous way.
